version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicare
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/medicare
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./Frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend

volumes:
  db_data:
