version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medicare
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@db:5432/medicare
      REDIS_URL: redis://redis:6379
    ports:
      - "5001:5000"
    depends_on:
      - db
      - redis
    

  frontend:
    build: ./Frontend
    ports:
      - "3000:4173"
    depends_on:
      - backend

volumes:
  db_data:

